'use client'
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/design-system";
import { MenuProvider } from "@/context/MenuContext";


// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <MenuProvider>
      <body>
      <Navbar/>
        {children}
        </body>
        </MenuProvider>
    </html>
  );
}
